- name: Test HAProxy source code installation
  hosts: host 
  vars:
          haproxy_url: http://www.haproxy.org/download/1.8/src/haproxy-1.8.11.tar.gz
          haproxy_version: haproxy-1.8.11
          haproxy_filename: "{{ haproxy_version }}.tar.gz"
          haproxy_directory: /home/vagrant/haproxy

  tasks:

          - name: Install dependencies
            become: True
            yum: name={{ item }}
            with_items:
                    - make
                    - gcc
                    - pcre-devel
                    -  openssl-devel
                    - zlib-devel
          

          - name: Create directory for HAProxy
            become_user: vagrant
            file:
                    path: "{{ haproxy_directory }}"
                    state: directory

          - name: Download HAProxy
            run_once: True
            local_action: get_url
            args:
                    url: "{{ haproxy_url }}"
                    dest: "/tmp/"
            vars:
                    ansible_become: False
                          
          - name: Unarchive HAProxy file
            unarchive:

                    src: "/tmp/{{ haproxy_version }}.tar.gz"
                    dest: "{{ haproxy_directory }}"

          - name: Add line
            lineinfile:
                    path: "{{ haproxy_directory }}/{{ haproxy_version }}/Makefile"
                    regexp: '^DESTDIR ='
                    line: 'DESTDIR = {{ haproxy_directory }}'




#          - meta: end_play

          - name: Compile source code
            make:
                    chdir: "{{ haproxy_directory }}/{{ haproxy_version }}"
                    params:
                            TARGET=linux2628
                            USE_PCRE=1
                            USE_ZLIB=1
                            USE_OPENSSL=1
                            DESTDIR={{ haproxy_directory }}

          - name: Install HAProxy
            make:
                    chdir: "{{ haproxy_directory }}/{{ haproxy_version }}"
                    target: install
